FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY producer.py .
# mock_data will be mounted as a volume by docker-compose

CMD ["python", "producer.py"]